// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = {
    Collections: {},
    Models: {},
    Views: {}
  };

  App.Collections.Standings = (function(_super) {
    __extends(Standings, _super);

    function Standings() {
      _ref = Standings.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Standings.prototype.url = "api/v1/standings";

    Standings.prototype.sortAttribute = 'rating';

    Standings.prototype.sortDescending = true;

    Standings.prototype.comparator = function(left, right) {
      var greaterValue, lessValue;
      left = left.get(this.sortAttribute);
      right = right.get(this.sortAttribute);
      lessValue = this.sortDescending ? -1 : 1;
      greaterValue = -lessValue;
      if (left < right) {
        return lessValue;
      } else if (left > right) {
        return greaterValue;
      } else {
        return 0;
      }
    };

    return Standings;

  })(Backbone.Collection);

  App.Views.PlayerStanding = (function(_super) {
    __extends(PlayerStanding, _super);

    function PlayerStanding() {
      _ref1 = PlayerStanding.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    PlayerStanding.prototype.tagName = 'tr';

    PlayerStanding.prototype.template = '#playerStandingsTemplate';

    return PlayerStanding;

  })(Marionette.ItemView);

  App.Views.Standings = (function(_super) {
    __extends(Standings, _super);

    function Standings() {
      _ref2 = Standings.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Standings.prototype.tagName = 'table';

    Standings.prototype.className = 'standings';

    Standings.prototype.template = '#standingsTemplate';

    Standings.prototype.itemView = App.Views.PlayerStanding;

    Standings.prototype.events = {
      'click th': 'onHeaderClick'
    };

    Standings.prototype.collectionEvents = {
      'sort': 'render'
    };

    Standings.prototype.onHeaderClick = function(e) {
      var sortAttribute;
      sortAttribute = $(e.target).data("sort");
      if (this.collection.sortAttribute === sortAttribute) {
        this.collection.sortDescending = !this.collection.sortDescending;
      } else {
        this.collection.sortAttribute = sortAttribute;
        this.collection.sortDescending = true;
      }
      return this.collection.sort();
    };

    return Standings;

  })(Marionette.CompositeView);

  window.Lunchkin = new Marionette.Application;

  Lunchkin.addInitializer(function() {
    return Lunchkin.addRegions({
      mainRegion: '#mainRegion'
    });
  });

  Lunchkin.addInitializer(function() {
    var collection, standings;
    collection = new App.Collections.Standings;
    collection.fetch();
    standings = new App.Views.Standings({
      collection: collection
    });
    return Lunchkin.mainRegion.show(standings);
  });

  $(function() {
    return Lunchkin.start();
  });

}).call(this);
